variables:
  FF_NETWORK_PER_BUILD: 1
  AWS_ACCESS_KEY_ID: \$AWS_ACCESS_KEY_ID
  AWS_REGION: \$AWS_REGION
  AWS_SECRET_ACCESS_KEY: \$AWS_SECRET_ACCESS_KEY
  DOCKER_HOST: tcp://docker:2375
  DOCKER_REGISTRY: \$DOCKER_REGISTRY
stages:
  - build
.build-docker-image:
  stage: build
  variables:
    DOCKER_REPOSITORY_NAME: \$SUBPROJECT
    DOCKER_REPOSITORY_URI: '\$DOCKER_REGISTRY/\$DOCKER_REPOSITORY_NAME'
  environment:
    name: production
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - name: docker:20.10.24-dind
      alias: docker
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t \$DOCKER_REPOSITORY_URI:\$CI_COMMIT_TAG --network=host
    $if(codeartifact_support_enabled.truthy)$
        --build-arg AWS_ACCESS_KEY_ID=\$AWS_ACCESS_KEY_ID
        --build-arg AWS_SECRET_ACCESS_KEY=\$AWS_SECRET_ACCESS_KEY
        --build-arg AWS_REGION=\$AWS_REGION
    $endif$
        --build-arg DOCKER_HOST=\$DOCKER_HOST
        -f ./\$SUBPROJECT/Dockerfile .
    - aws ecr get-login-password | docker login --username AWS --password-stdin \$DOCKER_REGISTRY
    - docker push \$DOCKER_REPOSITORY_URI:\$CI_COMMIT_TAG
build-server-image:
  extends: .build-docker-image
  variables:
    SUBPROJECT: $name;format="norm"$-server
  rules:
    - if: '\$CI_COMMIT_TAG != null'
      when: always
build-db-image:
  extends: .build-docker-image
  variables:
    SUBPROJECT: $name;format="norm"$-db
  rules:
    - if: '\$CI_COMMIT_TAG != null'
      when: manual
build-protobuf-idl:
  stage: build
  environment:
    name: production
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  before_script:
    - rm -f /etc/yum.repos.d/bintray-rpm.repo || true
    - curl -L https://www.scala-sbt.org/sbt-rpm.repo > sbt-rpm.repo
    - mv sbt-rpm.repo /etc/yum.repos.d/
    - yum -y install java-11-amazon-corretto.x86_64 sbt
  script:
    $if(codeartifact_support_enabled.truthy)$
    - sbt $name;format="norm"$-protobuf/codeArtifactPublish
    $else$
    - sbt $name;format="norm"$-protobuf/publish
    $endif$
  when: manual

